language: generic

sudo: required

services:
  - docker

notifications:
  email:
    recipients:
      - revett@cityofzion.io
    on_success: never
    on_failure: always

# Install step is skipped.
install: true

# Script step is run as part of a shell script as it requires a conditional.
script:
  ./scripts/travis.sh